import { type NextPage } from "next";
import Head from "next/head";
import { SurveyForm } from "~/components";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-stone-900 to-indigo-950">
        <SurveyForm />
      </main>
    </>
  );
};

export default Home;
